# SPDX-FileCopyrightText: 2024 Serpent OS Developers
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_compliance:
    runs-on: ubuntu-latest
    name: Run check

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
